[package]
name = "ffi-utils"
version = "0.1.0"
authors = [
    "Thibaut Lorrain <thibaut.lorrain@snips.ai>",
    "Kevin Lefevre <kevin.lefevre@snips.ai>",
]
edition = "2018"

[dependencies]
failure = "0.1"
failure-utils = { path = "../failure-utils" }
libc = "0.2"
