[package]
name = "ffi-convert"
version = "0.1.0"
authors = [
    "Thibaut Lorrain <thibaut.lorrain@snips.ai>",
    "Kevin Lefevre <kevin.lefevre@snips.ai>",
]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A collection of utilities to ease conversion between Rust and C-compatible data structures."
repository = "https://github.com/snipsco/snips-utils-rs"
readme = "../README.md"
keywords = ["ffi"]

[dependencies]
ffi-convert-derive = { path = "../ffi-convert-derive" }
failure = "0.1"
libc = "0.2"
